# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb3080b50fd9bf34c136a947a6fb1da87a591c593b145b64ae830db5f56f6032ecffa3562033fc4a2b246ec1e83773ab24fafcb60896711adc2ec2a6ec8f8bb8

test:
  secret_key_base: f38e84c27e0ee5cf924a639a107c68861782118031343b9c4f81ce838dd1b333b185551aba8934515797775d27a96921f75363a3e340f1dc67c4cb99eaf001d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
